# Site settings
title: don’t shoot
description: This is don't shoot.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dontshoot.at" # the base hostname & protocol for your site
permalink: /:title/
timezone: Europe/Vienna

paginate: 3
paginate_path: "/p:num"

markdown: kramdown

sass:
  # style: :compressed
  style: :compact
  sass_dir: assets/_sass